// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTq3rVdcAORkKaQ3pPhj3s2wptTV7DPG8',
    appId: '1:872700147849:web:4e9792db7970f693866e58',
    messagingSenderId: '872700147849',
    projectId: 'proyecto1-17401014',
    authDomain: 'proyecto1-17401014.firebaseapp.com',
    storageBucket: 'proyecto1-17401014.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArGELGSuWkc3eLeDnF7vOW9teUhdcI2CU',
    appId: '1:872700147849:android:3fd49e81107e0d61866e58',
    messagingSenderId: '872700147849',
    projectId: 'proyecto1-17401014',
    storageBucket: 'proyecto1-17401014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATE5CLzNwog7HjLIRrTz3ISY0t1RUJcqk',
    appId: '1:872700147849:ios:7b0eea5da3463d39866e58',
    messagingSenderId: '872700147849',
    projectId: 'proyecto1-17401014',
    storageBucket: 'proyecto1-17401014.appspot.com',
    iosClientId: '872700147849-kg1o3s934hptq3luv54egithupjnl09r.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto117401014',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATE5CLzNwog7HjLIRrTz3ISY0t1RUJcqk',
    appId: '1:872700147849:ios:7b0eea5da3463d39866e58',
    messagingSenderId: '872700147849',
    projectId: 'proyecto1-17401014',
    storageBucket: 'proyecto1-17401014.appspot.com',
    iosClientId: '872700147849-kg1o3s934hptq3luv54egithupjnl09r.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto117401014',
  );
}
